### ISSUE TITLE
Calling clear() for TextEditingController during validation does not work and causes error

### ISSUE THREAD

**Issue by nicodumdum** [adar2378/pin_code_fields#162]
Hi,

I'm trying to make it so that if the user inputs the wrong PIN, the app will clear the field, show the validation error message that it was mismatch, and run the error animation to get the attention of the user. My current code shows the validation error message and the error animation just fine, but the clearing of the field is not working, and an error shows up in the debug console.

In my `main.dart` code, I included a sample code for `TextFormField` for comparison that it works just fine for it.

I'm not really fussy in what order these three things happen, I just want them all to happen after the user completes typing the pin code. I hope you can help me with this issue.

Thanks!

<details>
<summary>main.dart</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:pin_code_fields/pin_code_fields.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _formKey = GlobalKey<FormState>();
  final _textController = TextEditingController();
  final _pinCodeController = TextEditingController();
  final _errorController = StreamController<ErrorAnimationType>();
  final _validPinCode = '123456';

  @override
  void dispose() {
    _textController.dispose();
    _errorController.close();
    super.dispose();
  }

  String _validateText(String text) {
    if (text != _validPinCode) {
      _textController.clear(); // This works just fine.
      return 'Mismatch';
    }
    return null;
  }

  String _validatePinCode(String pinCode) {
    if (pinCode.isNotEmpty && pinCode.length == 6) {
      if (pinCode != _validPinCode) {
        _pinCodeController.clear(); //! This is not working and causes error.
        _errorController.add(ErrorAnimationType.shake);
        return 'Mismatch';
      }
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Form(
        key: _formKey,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextFormField(
                controller: _textController,
                validator: (value) {
                  return _validateText(value);
                },
                onFieldSubmitted: (value) {
                  _formKey.currentState.validate();
                },
              ),
              PinCodeTextField(
                appContext: context,
                length: 6,
                obscureText: true,
                keyboardType: TextInputType.number,
                animationType: AnimationType.scale,
                errorAnimationController: _errorController,
                controller: _pinCodeController,
                validator: (value) {
                  print('Validated PIN code input { value: $value }');
                  return _validatePinCode(value);
                },
                onChanged: (value) {
                  print('Changed PIN code input { value: $value }');
                },
                onCompleted: (value) {
                  print('Completed PIN code input { value: $value }');
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Debug Console</summary>

```txt
Launching lib\main.dart on Mi A3 in debug mode...
 package:flutter_application_1/main.dart
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:5545/0p0Xdla6Bbs=/ws
I/AssistStructure(18908): Flattened final assist data: 432 bytes, containing 1 windows, 3 views
W/IInputConnectionWrapper(18908): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(18908): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(18908): getTextAfterCursor on inactive InputConnection
I/flutter (18908): Changed PIN code input { value: 1 }
I/flutter (18908): Validated PIN code input { value: 1 }
I/flutter (18908): Changed PIN code input { value: 11 }
I/flutter (18908): Validated PIN code input { value: 11 }
I/flutter (18908): Changed PIN code input { value: 111 }
I/flutter (18908): Validated PIN code input { value: 111 }
I/flutter (18908): Changed PIN code input { value: 1111 }
I/flutter (18908): Validated PIN code input { value: 1111 }
I/flutter (18908): Changed PIN code input { value: 11111 }
I/flutter (18908): Validated PIN code input { value: 11111 }
I/flutter (18908): Changed PIN code input { value: 111111 }
I/flutter (18908): Validated PIN code input { value: 111111 }
I/flutter (18908): Changed PIN code input { value:  }

[38;5;248m════════ Exception caught by foundation library ════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown while dispatching notifications for TextEditingController:[39;49m
setState() or markNeedsBuild() called during build.

[38;5;244mThis Form widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.[39;49m
[38;5;244mThe widget on which setState() or markNeedsBuild() was called was: Form-[LabeledGlobalKey<FormState>#e0c30][39;49m
    [38;5;244mstate: FormState#2ea20[39;49m
[38;5;244mThe widget which was currently being built when the offending call was made was: TextFormField[39;49m
    [38;5;244mdirty[39;49m
    [38;5;244mdependencies: [_InheritedTheme, _FormScope, _LocalizationsScope-[GlobalKey#a0495]][39;49m
    [38;5;244mstate: _TextFormFieldState#8bfe0[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      Element.markNeedsBuild.<anonymous closure>[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244m#1      Element.markNeedsBuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244m#2      State.setState[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244m#3      FormState._forceRebuild[39;49m
 package:flutter/…/widgets/form.dart
[38;5;244m#4      FormState._fieldDidChange[39;49m
 package:flutter/…/widgets/form.dart
[38;5;244m...[39;49m
[38;5;244mThe TextEditingController sending notification was: TextEditingController#61b8e(TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1)))[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
E/flutter (18908): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter (18908): This PinCodeTextField widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (18908): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (18908):   PinCodeTextField
E/flutter (18908): The widget which was currently being built when the offending call was made was:
E/flutter (18908):   TextFormField
[38;5;244mE/flutter (18908): #0      Element.markNeedsBuild.<anonymous closure>[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #1      Element.markNeedsBuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #2      State.setState[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #3      _PinCodeTextFieldState._setTextToInput[39;49m
 package:pin_code_fields/src/pin_code_fields.dart
[38;5;244mE/flutter (18908): #4      _PinCodeTextFieldState._assignController.<anonymous closure>[39;49m
 package:pin_code_fields/src/pin_code_fields.dart
[38;5;244mE/flutter (18908): #5      ChangeNotifier.notifyListeners[39;49m
 package:flutter/…/foundation/change_notifier.dart
[38;5;244mE/flutter (18908): #6      ValueNotifier.value=[39;49m
 package:flutter/…/foundation/change_notifier.dart
[38;5;244mE/flutter (18908): #7      TextEditingController.value=[39;49m
 package:flutter/…/widgets/editable_text.dart
[38;5;244mE/flutter (18908): #8      TextEditingController.clear[39;49m
 package:flutter/…/widgets/editable_text.dart
[38;5;248mE/flutter (18908): #9      _MyHomePageState._validatePinCode[39;49m
 package:flutter_application_1/main.dart
[38;5;248mE/flutter (18908): #10     _MyHomePageState.build.<anonymous closure>[39;49m
 package:flutter_application_1/main.dart
[38;5;244mE/flutter (18908): #11     FormFieldState._validate[39;49m
 package:flutter/…/widgets/form.dart
[38;5;244mE/flutter (18908): #12     FormFieldState.build[39;49m
 package:flutter/…/widgets/form.dart
[38;5;244mE/flutter (18908): #13     StatefulElement.build[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #14     ComponentElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #15     StatefulElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #16     Element.rebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #17     StatefulElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #18     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #19     ComponentElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #20     Element.rebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #21     ProxyElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #22     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #23     ComponentElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #24     StatefulElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #25     Element.rebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #26     StatefulElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #27     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #28     SingleChildRenderObjectElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #29     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #30     RenderObjectElement.updateChildren[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #31     MultiChildRenderObjectElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #32     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #33     SingleChildRenderObjectElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #34     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #35     SingleChildRenderObjectElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #36     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #37     ComponentElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #38     Element.rebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #39     StatelessElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #40     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #41     SingleChildRenderObjectElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #42     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #43     ComponentElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #44     StatefulElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #45     Element.rebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #46     StatefulElement.update[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #47     Element.updateChild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #48     ComponentElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #49     StatefulElement.performRebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #50     Element.rebuild[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #51     BuildOwner.buildScope[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (18908): #52     WidgetsBinding.drawFrame[39;49m
 package:flutter/…/widgets/binding.dart
[38;5;244mE/flutter (18908): #53     RendererBinding._handlePersistentFrameCallback[39;49m
 package:flutter/…/rendering/binding.dart
[38;5;244mE/flutter (18908): #54     SchedulerBinding._invokeFrameCallback[39;49m
 package:flutter/…/scheduler/binding.dart
[38;5;244mE/flutter (18908): #55     SchedulerBinding.handleDrawFrame[39;49m
 package:flutter/…/scheduler/binding.dart
[38;5;244mE/flutter (18908): #56     SchedulerBinding._handleDrawFrame[39;49m
 package:flutter/…/scheduler/binding.dart
[38;5;244mE/flutter (18908): #57     _rootRun (dart:async/zone.dart:1190:13)[39;49m
[38;5;244mE/flutter (18908): #58     _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m
[38;5;244mE/flutter (18908): #59     _CustomZone.runGuarded (dart:async/zone.dart:997:7)[39;49m
[38;5;244mE/flutter (18908): #60     _invoke (dart:ui/hooks.dart:251:10)[39;49m
[38;5;244mE/flutter (18908): #61     _drawFrame (dart:ui/hooks.dart:209:3)[39;49m
E/flutter (18908):
I/flutter (18908): Completed PIN code input { value: 111111 }
Application finished.
Exited (sigterm)
```

</details>

<details>
<summary>pubspec.yaml</summary>

```yaml
name: flutter_application_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^6.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
</details>

<details>
<summary>flutter doctor</summary>

```txt
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Nico\Desktop\PRJ\flutter_application_1> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale en-PH)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.   
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.53.2)        
[√] Connected device (1 available)  

! Doctor found issues in 1 category.
PS C:\Users\Nico\Desktop\PRJ\flutter_application_1> 
```
</details>
