### ISSUE TITLE
error padding not applying

### ISSUE THREAD

**Issue by MisterB2B** [adar2378/pin_code_fields#228]
I don't want the field to validate on every interaction, but only when I trigger by myself so I've set autovalidateMode to AutovalidateMode.disabled. BUT by doing this, the error message don't apply the errorTextSpace parameter wich is pretty ugly.

and is it possible to add an error text style parameter so I can change the error's text color ?

![image](https://user-images.githubusercontent.com/37023953/148703454-3b014282-29a8-438a-8cf7-6d5522acddfb.png)

**Comment by Add00w** [comment]
[This](https://github.com/adar2378/pin_code_fields/pull/230#issue-1101312841) pull request solves your issue.
Use from my repo  like bellow until they accept the pull request:
```
pin_code_fields:
    git:
      url: https://github.com/Add00w/pin_code_fields.git
      ref: develop
```
